#!/bin/bash

source "$(dirname "$0")/include.sh";

declare -A VALIDARGS
VALIDARGS=(["set"]="Set PHP version" ["install"]="Install PHP version" ["remove"]="Remove PHP version")

myname () {
  notice "CLI for PHP, aka CLI-P"
}

composehelp () {
  myname
  notice "Building help file";
  HELPFILE="$(dirname $0)/help.sh"

  echo "#!/bin/bash" > $HELPFILE
  echo "source \"\$(dirname \"$0\")/include.sh\";" >> $HELPFILE

  echo "eline \"$(basename $0) [setup|ansi|set|install|remove] [version]\"" >> $HELPFILE
  echo "info \"ansi\" \"Show ANSI banner (for fun)\"" >> $HELPFILE

  for file in $(ls -A $(dirname $0)/php-*);
  do
    eline "Adding" "${file}"
    OUTPUT=$(${file} shorthelp | sed "s/\x1B\[[0-9;]\{1,\}[A-Za-z]//g")
    echo "info \"$(echo ${OUTPUT::20} | xargs)\" \"${OUTPUT:21}\"" >> $HELPFILE
  done
}

help () {
    myname
    ${MYDIR}/help.sh
    exit 0
    eline "$(basename $0) [setup|ansi|set|install|remove] [version]"
    info "ansi" "Show ANSI banner (for fun)"
    for item in $(ls | grep "php-")
    #"${!VALIDARGS[@]}";
    do
      ${MYDIR}/${item} shorthelp
#      info "${item}" "${VALIDARGS[$item]}"
    done
}

case "$1" in
    "setup")
        myname
        cat cli-p.ansi
        ${MYDIR}/php-setup ${2}
        ;;

    "ansi")
        myname
        cat cli-p.ansi
        ;;

    "composehelp")
        composehelp
        ;;

    *)
        if [ -f "${MYDIR}/php-${1}" ]; then
          ${MYDIR}/php-${1} "${2}"
        else
          help
        fi
        ;;
esac