#!/bin/bash

source "$(dirname "$0")/include.sh";

help () {
    notice "CLI to PHP Bagiwi aka CLIP"
    eline "$(basename $0) [set|install|remove] [version]"
    info "set" "Set PHP version"
    info "install" "Install PHP version"
    info "remove" "Remove PHP version"
}

case "$1" in
    "set")
        ${MYDIR}/php-setver $2
        ;;

    "install")
        ${MYDIR}/php-install $2
        ;;

    "remove")
        ${MYDIR}/php-remove $2
        ;;

    *)
        help
        ;;
esac