#!/bin/bash

source "$(dirname "$0")/include.sh";

if [ -f "${VERFILELOC}" ]; then
  sline "Currently set to ${HIGHLIGHT}${CURVER}${RESET} - "
else
  sline "Currently no PHP version set - "
fi

if [ $# -eq 1 ]; then

	if [[ -d "${PHPDIR}/php-$1" ]]; then
		notice "Setting PHP version to" $1
		echo "$1" > ${MYDIR}/php.ver
	else
		error "$1 is not a valid version"
		newline
		listversions
	fi
else
	listversions
fi

