#!/bin/bash

source "$(dirname "$0")/include.sh";

if [ "$1" = "shorthelp" ]; then
  info "remove" "Remove PHP version"
  exit 0;
fi

remove () {
  info "Deleting version" $1
  		rm -rf "${2}"
  		if [ $? = 0 ]; then
  		  notice "Done"
  		else
  		  fail "Unable to remove version"
  		fi
}

notice "Remove PHP version"

if [ $# -eq 1 ]; then
  DELPHPDIR="${PHPDIR}/php-$1"
	if [[ -d "${DELPHPDIR}" ]]; then
	  info "You are about to remove version ${1}"
      read -r -p "Are you sure? [y/N] " response

      case "$response" in
          [yY]|[yY])
              remove ${1} ${DELPHPDIR}
              ;;

            *)
              echo "OK"
              ;;
      esac
	else
		error "$1 is not a valid version"
		newline
		listversions
	fi
else
	listversions
fi

