#!/bin/bash

source "$(dirname "$0")/include.sh";

if [ "$1" = "shorthelp" ]; then
  info "set" "Fix PHP version globally or locally"
  exit 0;
fi

if [ $# -eq 1 ]; then

	if [[ -d "${PHPDIR}/php-$1" ]]; then
		notice "Setting PHP version to" $1
		echo "$1" > ${MYDIR}/${PHPVERFILE}
	else
		error "$1 is not a valid version"
		newline
		listversions
	fi
else
	listversions
fi

